print('\nD:\\Coding\\NULP\\PRO\\lab1>mpiexec -n 16 PRO_lab1.exe\n')
print(' Shchudlo Vitalii | Hello from process 0\n')
print(' Shchudlo Vitalii | Hello from process 4\n')
print(' Shchudlo Vitalii | Hello from process 6\n')
print(' Shchudlo Vitalii | Hello from process 15\n')
print(' Shchudlo Vitalii | Hello from process 13\n')
print(' Shchudlo Vitalii | Hello from process 3\n')
print(' Shchudlo Vitalii | Hello from process 12\n')
print(' Shchudlo Vitalii | Hello from process 14\n')
print(' Shchudlo Vitalii | Hello from process 2\n')
print(' Shchudlo Vitalii | Hello from process 9\n')
print(' Shchudlo Vitalii | Hello from process 7\n')
print(' Shchudlo Vitalii | Hello from process 10\n')
print(' Shchudlo Vitalii | Hello from process 8\n')
print(' Shchudlo Vitalii | Hello from process 5\n')
print(' Shchudlo Vitalii | Hello from process 11\n')
print(' Shchudlo Vitalii | Hello from process 1\n')

